M48
; DRILL file KiCad 10.0.6 date 2026-09-05T19:52:01
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-05T19:52:01+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X109.61Y-118.545
X115.39Y-118.545
T2
X102.7Y-102.7
X122.3Y-102.7
M30
